AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/**/*
    - vendor/**/*
    - bin/*
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Max: 120
  Exclude:
    - config//*

Style/ClassAndModuleChildren:
  Exclude:
    - config//*
