default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  database: <%= ENV['DB_DATABASE_NAME'] %>
  host: <%= ENV['DB_HOST']%>
  port: <%= ENV['DB_PORT']%>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] %>_production

